/**
 * LastMileCoordinationScreen — dynamic transport options from Firestore.
 * Transport options are generated by Cloud Functions and stored in
 * transport_options/{tripId}_* — loaded via transportStore.
 *
 * Travelers can specify their desired pickup route/preferences
 * which are saved to Firestore for the operator/driver to see.
 */
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState, useEffect } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, Share, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { doc, onSnapshot, collection, query, where, limit, setDoc, getDoc, addDoc, serverTimestamp } from 'firebase/firestore';

import PersistentTabBar from '@/src/components/PersistentTabBar';
import { useAssistantStore } from '@/src/store/assistantStore';
import { useMobilityStore } from '@/src/store/mobilityStore';
import { useTripStore } from '@/src/store/tripStore';
import { useWeatherStore } from '@/src/store/weatherStore';
import { generateShareUpdate, refreshTripMonitoring } from '@/src/firebase/callables';
import { useAuthStore } from '@/src/store/useAuthStore';
import { getFirebaseFirestore } from '@/src/firebase/firebaseApp';

/* ── Helpers ─────────────────────────────────────────────────────────── */

function fmtDuration(sec: number): string {
  const mins = Math.round(sec / 60);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h ? `${h}h ${m}m` : `${m}m`;
}

const KIND_META: Record<string, { icon: string; color: string; label: string }> = {
  ride_hailing: { icon: 'car-sport', color: '#3B82F6', label: 'Ride hailing' },
  taxi: { icon: 'car', color: '#F59E0B', label: 'Taxi' },
  shuttle: { icon: 'bus', color: '#22C55E', label: 'Shuttle' },
  rental_car: { icon: 'car-outline', color: '#8B5CF6', label: 'Car rental' },
  public_transit: { icon: 'train', color: '#14B8A6', label: 'Public transit' },
};

const STATUS_CFG = {
  available: { color: '#22C55E', label: 'Available' },
  limited: { color: '#F59E0B', label: 'Limited' },
  unavailable: { color: '#EF4444', label: 'Unavailable' },
};

/* ── Screen ──────────────────────────────────────────────────────────── */

export default function LastMileCoordinationScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { tripId } = useLocalSearchParams<{ tripId: string }>();
  const uid = useAuthStore((s) => s.token);
  const [refreshing, setRefreshing] = useState(false);
  const [sharing, setSharing] = useState(false);

  const trips = useTripStore((s) => s.trips);
  const trip = useMemo(
    () => trips.find((t) => String(t.id) === String(tripId)) ?? trips[0] ?? null,
    [tripId, trips],
  );

  const mobility = useMobilityStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const weather = useWeatherStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const best = mobility?.bestRoute ?? null;

  // ── Pickup preferences state ───────────────────────────────────────
  const [pickupLocation, setPickupLocation] = useState('');
  const [dropoffLocation, setDropoffLocation] = useState('');
  const [driverNotes, setDriverNotes] = useState('');
  const [preferencesLoaded, setPreferencesLoaded] = useState(false);
  const [savingPrefs, setSavingPrefs] = useState(false);
  const [prefsSaved, setPrefsSaved] = useState(false);

  // ── Assignment state ───────────────────────────────────────────────
  const [assignment, setAssignment] = useState<any>(null);
  const [loadingAssignment, setLoadingAssignment] = useState(false);

  const dest = trip?.destinationAirport?.city ?? trip?.to ?? 'destination';

  // Load existing pickup preferences from Firestore
  useEffect(() => {
    if (!trip?.id || !uid) return;
    const db = getFirebaseFirestore();
    const prefsRef = doc(db, 'tripPickupPreferences', trip.id);
    getDoc(prefsRef).then((snap) => {
      if (snap.exists()) {
        const data = snap.data();
        setPickupLocation(data.pickupLocation || '');
        setDropoffLocation(data.dropoffLocation || '');
        setDriverNotes(data.driverNotes || '');
      }
      setPreferencesLoaded(true);
    }).catch(() => {
      setPreferencesLoaded(true);
    });
  }, [trip?.id, uid]);

  // Listen to active assignment for this trip
  useEffect(() => {
    if (!trip?.id || !uid) return;
    setLoadingAssignment(true);
    const db = getFirebaseFirestore();
    const q = query(
      collection(db, 'assignments'),
      where('travelerId', '==', uid),
      where('tripId', '==', trip.id),
      limit(1)
    );
    const unsub = onSnapshot(q, (snap) => {
      if (!snap.empty) {
        setAssignment({ id: snap.docs[0].id, ...snap.docs[0].data() });
      } else {
        setAssignment(null);
      }
      setLoadingAssignment(false);
    }, (err) => {
      console.log('Assignment listener error:', err);
      setLoadingAssignment(false);
    });
    return () => unsub();
  }, [trip?.id, uid]);

  // ── Save pickup preferences ────────────────────────────────────────
  async function handleSavePreferences() {
    if (!trip?.id || !uid) return;
    setSavingPrefs(true);
    try {
      const db = getFirebaseFirestore();
      await setDoc(doc(db, 'tripPickupPreferences', trip.id), {
        tripId: trip.id,
        travelerId: uid,
        pickupLocation: pickupLocation.trim(),
        dropoffLocation: dropoffLocation.trim(),
        driverNotes: driverNotes.trim(),
        updatedAt: serverTimestamp(),
      });
      setPrefsSaved(true);
      setTimeout(() => setPrefsSaved(false), 3000);
    } catch (e: any) {
      Alert.alert('Failed to save', e?.message ?? 'Please try again.');
    } finally {
      setSavingPrefs(false);
    }
  }

  async function handleRefresh() {
    if (!trip || !uid || refreshing) return;
    setRefreshing(true);
    try {
      await refreshTripMonitoring(trip.id);
    } catch (e: any) {
      Alert.alert('Refresh failed', e?.message ?? 'Please try again.');
    } finally {
      setRefreshing(false);
    }
  }

  async function handleShare() {
    if (!trip) return;
    setSharing(true);
    try {
      const { shareText } = await generateShareUpdate(trip.id);
      await Share.share({ message: shareText, title: trip.title });
    } catch {
      await Share.share({ message: `Last-mile update for ${trip?.title}`, title: trip?.title ?? 'TICS' }).catch(() => { });
    } finally {
      setSharing(false);
    }
  }

  const handleCallDriver = async () => {
    if (!assignment?.driverPhone) {
      Alert.alert('Error', 'Driver phone number not available');
      return;
    }

    const phone = assignment.driverPhone.startsWith('0')
      ? `256${assignment.driverPhone.substring(1)}`
      : assignment.driverPhone;
    const url = `tel:${phone}`;

    const supported = await Linking.canOpenURL(url);

    if (supported) {
      await Linking.openURL(url);
    } else {
      Alert.alert('Error', 'Unable to open phone dialer');
    }
  };

  const handleWhatsAppDriver = async () => {
    if (!assignment?.driverPhone) {
      Alert.alert('Error', 'Driver phone number not available');
      return;
    }

    const phone = assignment.driverPhone.replace(/[^\d]/g, '');

    // Include pickup preferences in the message if set
    let extraContext = '';
    if (pickupLocation) extraContext += `\nPickup: ${pickupLocation}`;
    if (dropoffLocation) extraContext += `\nDropoff: ${dropoffLocation}`;
    if (driverNotes) extraContext += `\nNotes: ${driverNotes}`;

    const message = encodeURIComponent(
      `Hello ${assignment.driverName}, I am your assigned traveler.${extraContext}`
    );

    const whatsappUrl = `whatsapp://send?phone=${phone}&text=${message}`;

    const supported = await Linking.canOpenURL(whatsappUrl);

    if (supported) {
      await Linking.openURL(whatsappUrl);
    } else {
      Alert.alert(
        'WhatsApp Not Installed',
        'Please install WhatsApp to contact the driver.'
      );
    }
  };

  return (
    <View className="flex-1" style={{ paddingTop: insets.top + 8 }}>
      {/* Header */}
      <View className='p-2 mb-4 flex-row items-center gap-3 bg-tics-amber/25 border border-tics-amber/10 rounded-full'>
        <View style={{ flexDirection: 'row', gap: 8 }}>
          <Pressable
            onPress={() => router.back()}
            className="bg-tics-amber/35 border border-tics-amber/20 rounded-full"
            style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
          >
            <Ionicons name="chevron-back" size={20} color="rgba(248,250,252,0.9)" />
          </Pressable>
          <View
            className='border border-tics-purple rounded-full'
            style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}>
            <Ionicons name="car" size={18} color="#8B5CF6" />
          </View>
        </View>
        <View style={{ flex: 1 }}>
          <Text style={{ fontFamily: 'Syne_700Bold', color: '#f8fafc', fontSize: 17 }}>Last-Mile</Text>
          <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 11 }} numberOfLines={1}>
            {trip?.title ?? 'Ground transport'}
          </Text>
        </View>
        <Pressable
          onPress={handleShare}
          disabled={sharing}
          className="bg-tics-amber/35 border border-tics-amber/20 rounded-full"
          style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
        >
          {sharing ? <ActivityIndicator size={14} color="#fff" /> : <Ionicons name="share-social-outline" size={17} color="#fff" />}
        </Pressable>
        <Pressable
          onPress={handleRefresh}
          disabled={refreshing}
          style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
          className='rounded-full bg-tics-amber/35 border border-tics-amber/20'
        >
          {refreshing ? <ActivityIndicator size={14} color="#fff" /> : <Ionicons name="refresh" size={17} color="#fff" />}
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={{ gap: 14, paddingHorizontal: 8, paddingBottom: 13 }} showsVerticalScrollIndicator={false}>

        {/* Route summary */}
        <View className='rounded-4xl bg-tics-amber/25 border border-tics-amber/10' style={{ padding: 20 }}>
          <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#A78BFA', fontSize: 11, letterSpacing: 0.8, marginBottom: 12 }}>
            ROUTE COORDINATION
          </Text>

          <Text style={{ fontFamily: 'Syne_700Bold', color: '#f8fafc', fontSize: 16 }}>
            {trip?.to ? `Arriving at ${dest}` : 'Add a trip to enable last-mile coordination'}
          </Text>

          {/* Best route from mobility store */}
          <View className='rounded-3xl' style={{ marginTop: 14, borderWidth: 1, borderColor: 'rgba(139,92,246,0.25)', backgroundColor: 'rgba(139,92,246,0.08)', padding: 14 }}>
            <Text style={{ fontFamily: 'Syne_500Medium', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              COMPUTED ROUTE
            </Text>
            <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#f8fafc', fontSize: 14 }}>
              {best
                ? `${fmtDuration(best.durationSec)} · ${(best.distanceMeters / 1000).toFixed(1)} km`
                : 'Route computed after destination coordinates are set'}
            </Text>
            {mobility?.origin?.label && mobility?.destination?.label && (
              <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginTop: 4 }}>
                {mobility.origin.label} → {mobility.destination.label}
              </Text>
            )}
          </View>

          {/* Weather at destination */}
          {weather && weather.tempC != null && (
            <View style={{ marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              <Ionicons name="partly-sunny" size={16} color="#FBBF24" />
              <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12 }}>
                {dest}: {Math.round(weather.tempC)}°C, {weather.description ?? 'conditions unknown'}
                {weather.riskScore >= 3 ? ' — allow extra travel time' : ''}
              </Text>
            </View>
          )}

          {/* Action buttons */}
          <View className='flex-1 w-full' style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
            <Pressable
              onPress={() => trip && router.push(({ pathname: `/trips/${trip.id}/map` } as any))}
              className='bg-tics-amber/35 border border-tics-amber/20 items-center p-6 rounded-full flex-1'>
              <Text style={{ fontFamily: 'Syne_700Bold', color: '#fff', fontSize: 13 }}>View map</Text>
            </Pressable>
            <Pressable
              onPress={handleShare}
              disabled={sharing}
              className="border border-[#96C7B3]/50 bg-white/[0.06] items-center p-6 rounded-full flex-1">
              <Text style={{ fontFamily: 'Syne_500Medium', color: 'rgba(248,250,252,0.8)', fontSize: 13 }}>Share update</Text>
            </Pressable>
          </View>
        </View>

        {/* ── My Pickup Preferences (Traveler-specified route) ────── */}
        <View className='bg-tics-amber/25 border border-tics-amber/10 rounded-4xl' style={{ padding: 20 }}>
          <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#F59E0B', fontSize: 11, letterSpacing: 0.8, marginBottom: 14 }}>
            MY PICKUP PREFERENCES
          </Text>
          <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginBottom: 14 }}>
            Tell the operator and driver your preferred pickup route and any special instructions.
          </Text>

          {/* Pickup Location */}
          <View style={{ marginBottom: 14 }}>
            <Text className='ml-2' style={{ fontFamily: 'Syne_500Medium', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              PICKUP LOCATION
            </Text>
            <TextInput
              className='rounded-full p-5'
              style={{
                backgroundColor: 'rgba(255,255,255,0.06)',
                borderWidth: 1,
                borderColor: 'rgba(255,255,255,0.25)',
                color: '#f8fafc',
                fontSize: 14,
                fontFamily: 'Syne_500Medium',
              }}
              placeholder="e.g. Arrivals gate B, airport taxi bay"
              placeholderTextColor="#64748b"
              value={pickupLocation}
              onChangeText={setPickupLocation}
              multiline={false}
            />
          </View>

          {/* Dropoff Location */}
          <View style={{ marginBottom: 14 }}>
            <Text className='ml-2' style={{ fontFamily: 'Syne_500Medium', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              DROPOFF / DESTINATION
            </Text>
            <TextInput
            className='rounded-full p-5'
              style={{
                backgroundColor: 'rgba(255,255,255,0.06)',
                borderWidth: 1,
                borderColor: 'rgba(255,255,255,0.25)',
                color: '#f8fafc',
                fontSize: 14,
                fontFamily: 'Syne_500Medium',
              }}
              placeholder="e.g. Nairobi CBD, specific hotel or area"
              placeholderTextColor="#64748b"
              value={dropoffLocation}
              onChangeText={setDropoffLocation}
              multiline={false}
            />
          </View>

          {/* Notes for Driver */}
          <View style={{ marginBottom: 14 }}>
            <Text className='ml-2' style={{ fontFamily: 'Syne_500Medium', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              NOTES FOR DRIVER
            </Text>
            <TextInput
              className='rounded-3xl p-4'
              style={{
                backgroundColor: 'rgba(255,255,255,0.06)',
                borderWidth: 1,
                borderColor: 'rgba(255,255,255,0.25)',
                color: '#f8fafc',
                fontSize: 14,
                fontFamily: 'Syne_500Medium',
                minHeight: 80,
                textAlignVertical: 'top',
              }}
              placeholder="e.g. I have 2 large suitcases, please wait at arrivals"
              placeholderTextColor="#64748b"
              value={driverNotes}
              onChangeText={setDriverNotes}
              multiline
            />
          </View>

          <Pressable
            onPress={handleSavePreferences}
            disabled={savingPrefs}
            className='rounded-full p-6'
            style={{
              backgroundColor: prefsSaved ? 'rgba(34,197,94,0.2)' : 'rgba(245,158,11,0.3)',
              borderWidth: 1,
              borderColor: prefsSaved ? 'rgba(34,197,94,0.3)' : 'rgba(245,158,11,0.2)',
              alignItems: 'center',
              justifyContent: 'center',
              flexDirection: 'row',
              gap: 8,
            }}
          >
            {savingPrefs ? (
              <ActivityIndicator size={16} color="#F59E0B" />
            ) : prefsSaved ? (
              <>
                <Ionicons name="checkmark-circle" size={18} color="#22C55E" />
                <Text style={{ fontFamily: 'Syne_700Bold', color: '#22C55E', fontSize: 13 }}>Saved!</Text>
              </>
            ) : (
              <>
                <Ionicons name="save-outline" size={18} color="#fff" />
                <Text style={{ fontFamily: 'Syne_700Bold', color: '#fff', fontSize: 13 }}>
                  {pickupLocation || dropoffLocation || driverNotes ? 'Update Preferences' : 'Save Preferences'}
                </Text>
              </>
            )}
          </Pressable>
        </View>

        {/* My Pickup / Assignment Section */}
        {loadingAssignment ? (
          <View className="rounded-4xl" style={{ backgroundColor: 'rgba(59,130,246,0.08)', padding: 20, borderWidth: 1, borderColor: 'rgba(59,130,246,0.15)', alignItems: 'center' }}>
            <ActivityIndicator size="small" color="#60A5FA" />
            <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginTop: 8 }}>Loading pickup details...</Text>
          </View>
        ) : assignment ? (
          <View
            style={{ padding: 15, }}
            className='bg-tics-amber/25 border border-tics-amber/10 rounded-4xl'
          >
            <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#22C55E', fontSize: 11, letterSpacing: 0.8, marginBottom: 12 }}>
              PICKUP ASSIGNED
            </Text>

            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 }}>
              <View className='rounded-full' style={{ width: 44, height: 44, backgroundColor: 'rgba(34,197,94,0.25)', alignItems: 'center', justifyContent: 'center' }}>
                <Ionicons name="car" size={22} color="#22C55E" />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={{ fontFamily: 'Syne_700Bold', color: '#f8fafc', fontSize: 15 }}>
                  {assignment.driverName || 'Driver assigned'}
                </Text>
                <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginTop: 2 }}>
                  {assignment.vehicle || ''} {assignment.plateNumber ? `(${assignment.plateNumber})` : ''}
                </Text>
              </View>
            </View>

            <View style={{ gap: 8 }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <Ionicons name="call" size={16} color="#60A5FA" />
                <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 13 }}>
                  {assignment.driverPhone || 'N/A'}
                </Text>
              </View>

              {assignment.eta && (
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Ionicons name="time" size={16} color="#60A5FA" />
                  <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 13 }}>
                    ETA: {new Date(assignment.eta).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hour12: true })}
                  </Text>
                </View>
              )}

              {assignment.pickupLocation && (
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Ionicons name="location" size={16} color="#60A5FA" />
                  <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 13 }}>
                    {assignment.pickupLocation}
                  </Text>
                </View>
              )}

              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <Ionicons name="checkmark-circle" size={16} color="#22C55E" />
                <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#22C55E', fontSize: 12, textTransform: 'capitalize' }}>
                  {assignment.status || 'Assigned'}
                </Text>
              </View>
            </View>

            {/* Quick Actions */}
            <View style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
              {assignment.driverPhone && (
                <Pressable
                  onPress={handleCallDriver}
                  className='bg-tics-green/30 border border-tics-green/20 flex-1 flex-row items-center justify-center gap-2 rounded-full p-4'
                >
                  <Ionicons name="call" size={18} color="#22C55E" />
                  <Text style={{ fontFamily: 'Syne_700Bold', color: '#22C55E', fontSize: 11, marginTop: 4 }}>Call</Text>
                </Pressable>
              )}
              <Pressable
                onPress={handleWhatsAppDriver}
                className='bg-tics-green/30 border border-tics-green/20 flex-1 flex-row items-center justify-center gap-2 rounded-full p-4'
              >
                <Ionicons name="logo-whatsapp" size={18} color="#25D366" />
                <Text style={{ fontFamily: 'Syne_700Bold', color: '#25D366', fontSize: 11, marginTop: 4 }}>WhatsApp</Text>
              </Pressable>
            </View>

            {/* Start Ride button — navigates to live tracking */}
            <Pressable
              onPress={() => {
                const aId = assignment?.id || '';
                const tId = trip?.id || '';
                router.push({
                  pathname: '/last-mile/tracking' as any,
                  params: { assignmentId: aId, tripId: tId }
                } as any);
              }}
              style={{
                marginTop: 12,
                borderRadius: 99,
                backgroundColor: 'rgba(59,130,246,0.25)',
                borderWidth: 1,
                borderColor: 'rgba(59,130,246,0.3)',
                paddingVertical: 16,
                alignItems: 'center',
                justifyContent: 'center',
                flexDirection: 'row',
                gap: 8,
              }}
            >
              <Ionicons name="navigate" size={18} color="#60A5FA" />
              <Text style={{ fontFamily: 'Syne_700Bold', color: '#60A5FA', fontSize: 13 }}>
                Start Ride — Live Tracking
              </Text>
            </Pressable>

            {/* Show saved preferences in assignment section */}
            {(pickupLocation || dropoffLocation || driverNotes) && (
              <View style={{ marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)' }}>
                <Text style={{ fontFamily: 'Syne_500Medium', color: '#F59E0B', fontSize: 10, letterSpacing: 0.8, marginBottom: 8 }}>
                  YOUR PREFERENCES
                </Text>
                {pickupLocation ? (
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 }}>
                    <Ionicons name="location" size={14} color="#F59E0B" />
                    <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 12 }}>
                      Pickup: {pickupLocation}
                    </Text>
                  </View>
                ) : null}
                {dropoffLocation ? (
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 }}>
                    <Ionicons name="navigate" size={14} color="#F59E0B" />
                    <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 12 }}>
                      Dropoff: {dropoffLocation}
                    </Text>
                  </View>
                ) : null}
                {driverNotes ? (
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                    <Ionicons name="document-text" size={14} color="#F59E0B" />
                    <Text style={{ fontFamily: 'Syne_500Medium', color: '#e2e8f0', fontSize: 12 }} numberOfLines={2}>
                      Notes: {driverNotes}
                    </Text>
                  </View>
                ) : null}
              </View>
            )}
          </View>
        ) : (
          <View className='bg-tics-amber/25 border border-tics-amber/10 rounded-4xl' style={{ padding: 20, alignItems: 'center', gap: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' }}>
            <Ionicons name="car-outline" size={32} color="rgba(248,250,252,0.15)" />
            <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#94a3b8', fontSize: 13 }}>
              No pickup assigned yet
            </Text>
            <Text style={{ fontFamily: 'Syne_500Medium', color: '#64748b', fontSize: 11, textAlign: 'center', lineHeight: 16 }}>
              When an operator assigns a driver, you'll see the details here.
            </Text>
          </View>
        )}

        {/* Ask AI */}
        {trip && (
          <Pressable onPress={() => {
            const msg = `[Last Mile Planning]\nI'm arriving at ${dest}${trip.flightNumber ? ` on flight ${trip.flightNumber}` : ''}${trip.arrivalTime ? ` at ${new Date(trip.arrivalTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : ''}. The weather at destination is ${weather ? `${Math.round(weather.tempC ?? 0)}°C, ${weather.description ?? 'unknown'}` : 'unknown'}.\n\nPlease help me plan my last mile:\n1. What's the best transport option from ${dest} airport?\n2. Estimated costs and travel times\n3. How to book or arrange pickup\n4. Any tips for navigating the airport arrival area`;
            useAssistantStore.getState().setPendingMessage(msg, trip.id);
            router.push('/assistant' as any);
          }}>
            <View
              className='bg-tics-amber/35 border border-tics-amber/20 rounded-full p-6'
              style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
              <Ionicons name="sparkles-outline" size={18} color="#fff" />
              <Text style={{ fontFamily: 'Syne_700Bold', color: '#fff', fontSize: 13 }}>
                Ask AI to plan my last mile
              </Text>
            </View>
          </Pressable>
        )}

      </ScrollView>
      <PersistentTabBar />
    </View>
  );
}