/**
 * LastMileCoordinationScreen — dynamic transport options from Firestore.
 * Transport options are generated by Cloud Functions and stored in
 * transport_options/{tripId}_* — loaded via transportStore.
 */
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Share, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import PersistentTabBar from '@/src/components/PersistentTabBar';
import { useMobilityStore } from '@/src/store/mobilityStore';
import { useTripStore } from '@/src/store/tripStore';
import { useTransportStore, selectTransportOpts } from '@/src/store/transportStore';
import { useWeatherStore } from '@/src/store/weatherStore';
import { generateShareUpdate, refreshTripMonitoring } from '@/src/firebase/callables';
import { useAuthStore } from '@/src/store/useAuthStore';

/* ── Helpers ─────────────────────────────────────────────────────────── */

function fmtDuration(sec: number): string {
  const mins = Math.round(sec / 60);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h ? `${h}h ${m}m` : `${m}m`;
}

const KIND_META: Record<string, { icon: string; color: string; label: string }> = {
  ride_hailing: { icon: 'car-sport', color: '#3B82F6', label: 'Ride hailing' },
  taxi: { icon: 'car', color: '#F59E0B', label: 'Taxi' },
  shuttle: { icon: 'bus', color: '#22C55E', label: 'Shuttle' },
  rental_car: { icon: 'car-outline', color: '#8B5CF6', label: 'Car rental' },
  public_transit: { icon: 'train', color: '#14B8A6', label: 'Public transit' },
};

const STATUS_CFG = {
  available: { color: '#22C55E', label: 'Available' },
  limited: { color: '#F59E0B', label: 'Limited' },
  unavailable: { color: '#EF4444', label: 'Unavailable' },
};

/* ── Screen ──────────────────────────────────────────────────────────── */

export default function LastMileCoordinationScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { tripId } = useLocalSearchParams<{ tripId: string }>();
  const uid = useAuthStore((s) => s.token);
  const [refreshing, setRefreshing] = useState(false);
  const [sharing, setSharing] = useState(false);

  const trips = useTripStore((s) => s.trips);
  const trip = useMemo(
    () => trips.find((t) => String(t.id) === String(tripId)) ?? trips[0] ?? null,
    [tripId, trips],
  );

  const mobility = useMobilityStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const weather = useWeatherStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const transportOpts = useTransportStore(selectTransportOpts(trip?.id));
  const best = mobility?.bestRoute ?? null;

  const dest = trip?.destinationAirport?.city ?? trip?.to ?? 'destination';

  async function handleRefresh() {
    if (!trip || !uid || refreshing) return;
    setRefreshing(true);
    try {
      await refreshTripMonitoring(trip.id);
    } catch (e: any) {
      Alert.alert('Refresh failed', e?.message ?? 'Please try again.');
    } finally {
      setRefreshing(false);
    }
  }

  async function handleShare() {
    if (!trip) return;
    setSharing(true);
    try {
      const { shareText } = await generateShareUpdate(trip.id);
      await Share.share({ message: shareText, title: trip.title });
    } catch {
      await Share.share({ message: `Last-mile update for ${trip?.title}`, title: trip?.title ?? 'TICS' }).catch(() => { });
    } finally {
      setSharing(false);
    }
  }

  return (
    <View className="flex-1" style={{ paddingTop: insets.top + 8 }}>
      {/* Header */}
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 8, paddingBottom: 12 }}>
        <View style={{ flexDirection: 'row', gap: 8 }}>
          <Pressable
            onPress={() => router.back()}
            className="border border-[#96C7B3]/50 bg-white/[0.06]"
            style={{ width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }}
          >
            <Ionicons name="chevron-back" size={20} color="rgba(248,250,252,0.9)" />
          </Pressable>
          <View
            className='border border-tics-purple'
            style={{ width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12, }}>
            <Ionicons name="car" size={18} color="#8B5CF6" />
          </View>
        </View>
        <View style={{ flex: 1 }}>
          <Text style={{ fontFamily: 'Syne_700Bold', color: '#f8fafc', fontSize: 18 }}>Last-Mile</Text>
          <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 11 }} numberOfLines={1}>
            {trip?.title ?? 'Ground transport'}
          </Text>
        </View>
        <Pressable
          onPress={handleShare}
          disabled={sharing}
          className="bg-tics-amber"
          style={{ width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12, }}
        >
          {sharing ? <ActivityIndicator size={14} color="rgba(248,250,252,0.7)" /> : <Ionicons name="share-social-outline" size={17} color="#000" />}
        </Pressable>
        <Pressable
          onPress={handleRefresh}
          disabled={refreshing}
          style={{ width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#F59E0B' }}
        >
          {refreshing ? <ActivityIndicator size={14} color="rgba(248,250,252,0.7)" /> : <Ionicons name="refresh" size={17} color="rgba(10,11,30,0.9)" />}
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={{ gap: 14, paddingHorizontal: 8, paddingBottom: 112 }} showsVerticalScrollIndicator={false}>

        {/* Route summary */}
        <View style={{ borderRadius: 18, backgroundColor: 'rgba(139,92,246,0.30)', padding: 20 }}>
          <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#A78BFA', fontSize: 11, letterSpacing: 0.8, marginBottom: 12 }}>
            ROUTE COORDINATION
          </Text>

          <Text style={{ fontFamily: 'Syne_700Bold', color: '#f8fafc', fontSize: 16 }}>
            {trip?.to ? `Arriving at ${dest}` : 'Add a trip to enable last-mile coordination'}
          </Text>

          {/* Best route from mobility store */}
          <View style={{ marginTop: 14, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(139,92,246,0.25)', backgroundColor: 'rgba(139,92,246,0.08)', padding: 14 }}>
            <Text style={{ fontFamily: 'Syne_500Medium', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              COMPUTED ROUTE
            </Text>
            <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#f8fafc', fontSize: 14 }}>
              {best
                ? `${fmtDuration(best.durationSec)} · ${(best.distanceMeters / 1000).toFixed(1)} km`
                : 'Route computed after destination coordinates are set'}
            </Text>
            {mobility?.origin?.label && mobility?.destination?.label && (
              <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginTop: 4 }}>
                {mobility.origin.label} → {mobility.destination.label}
              </Text>
            )}
          </View>

          {/* Weather at destination */}
          {weather && weather.tempC != null && (
            <View style={{ marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              <Ionicons name="partly-sunny" size={16} color="#FBBF24" />
              <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12 }}>
                {dest}: {Math.round(weather.tempC)}°C, {weather.description ?? 'conditions unknown'}
                {weather.riskScore >= 3 ? ' — allow extra travel time' : ''}
              </Text>
            </View>
          )}

          {/* Action buttons */}
          <View style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
            <Pressable
              onPress={() => trip && router.push(({ pathname: `/trips/${trip.id}/map` } as any))}
              style={{ flex: 1, borderRadius: 12, backgroundColor: '#F59E0B', paddingVertical: 13, alignItems: 'center' }}
            >
              <Text style={{ fontFamily: 'Syne_700Bold', color: 'rgba(10,11,30,0.9)', fontSize: 13 }}>View map</Text>
            </Pressable>
            <Pressable
              onPress={handleShare}
              disabled={sharing}
              className="border border-[#96C7B3]/50 bg-white/[0.06]"
              style={{ flex: 1, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.05)', paddingVertical: 13, alignItems: 'center' }}
            >
              <Text style={{ fontFamily: 'Syne_500Medium', color: 'rgba(248,250,252,0.8)', fontSize: 13 }}>Share update</Text>
            </Pressable>
          </View>
        </View>

        {/* Transport options from Firestore (generated by Cloud Functions) */}
        <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#94a3b8', fontSize: 11, letterSpacing: 0.8 }}>
          TRANSPORT OPTIONS
        </Text>

        {transportOpts.length > 0 ? (
          transportOpts.map((opt) => {
            const meta = KIND_META[opt.kind] ?? KIND_META.ride_hailing!;
            const statusCfg = STATUS_CFG[opt.status ?? 'available'] ?? STATUS_CFG.available;
            return (
              <View
                key={opt.id}
                style={{ borderRadius: 16, borderWidth: 1, borderColor: `${meta.color}25`, backgroundColor: `${meta.color}08`, padding: 16 }}
              >
                <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                    <View style={{ width: 44, height: 44, borderRadius: 12, backgroundColor: `${meta.color}20`, alignItems: 'center', justifyContent: 'center' }}>
                      <Ionicons name={meta.icon as any} size={20} color={meta.color} />
                    </View>
                    <View>
                      <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#f8fafc', fontSize: 14 }}>
                        {opt.title}
                      </Text>
                      <Text style={{ fontFamily: 'Syne_500Medium', color: '#94a3b8', fontSize: 12, marginTop: 2 }}>
                        {opt.etaMinutes != null ? `~${opt.etaMinutes} min` : 'ETA varies'}
                        {opt.estimatedCost ? ` · ${opt.estimatedCost}` : ''}
                      </Text>
                    </View>
                  </View>
                  <View style={{ borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, backgroundColor: `${statusCfg.color}20` }}>
                    <Text style={{ fontFamily: 'Syne_700Bold', color: statusCfg.color, fontSize: 11 }}>
                      {statusCfg.label}
                    </Text>
                  </View>
                </View>
              </View>
            );
          })
        ) : (
          <View style={{ borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: 'rgba(255,255,255,0.04)', padding: 18, alignItems: 'center', gap: 10 }}>
            <Ionicons name="car-outline" size={32} color="rgba(248,250,252,0.15)" />
            <Text style={{ fontFamily: 'Syne_600SemiBold', color: '#94a3b8', fontSize: 14 }}>
              No transport options yet
            </Text>
            <Text style={{ fontFamily: 'Syne_500Medium', color: '#64748b', fontSize: 12, textAlign: 'center', lineHeight: 18 }}>
              Transport options are generated automatically when your arrival is within 3 hours. Tap refresh to check now.
            </Text>
            <Pressable
              onPress={handleRefresh}
              disabled={refreshing}
              style={{ borderRadius: 12, borderWidth: 1, borderColor: 'rgba(59,130,246,0.3)', backgroundColor: 'rgba(59,130,246,0.1)', paddingHorizontal: 20, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }}
            >
              {refreshing ? <ActivityIndicator size={14} color="#60A5FA" /> : <Ionicons name="refresh" size={16} color="#60A5FA" />}
              <Text style={{ fontFamily: 'Syne_700Bold', color: '#60A5FA', fontSize: 12 }}>
                {refreshing ? 'Loading…' : 'Run monitoring cycle'}
              </Text>
            </Pressable>
          </View>
        )}

        {/* Ask AI */}
        {trip && (
          <Pressable onPress={() => router.push(({ pathname: '/assistant', params: { tripId: trip.id } } as any))}>
            <View style={{ borderRadius: 14, borderWidth: 1, borderColor: 'rgba(59,130,246,0.25)', backgroundColor: 'rgba(59,130,246,0.07)', paddingVertical: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
              <Ionicons name="sparkles-outline" size={18} color="#60A5FA" />
              <Text style={{ fontFamily: 'Syne_700Bold', color: '#60A5FA', fontSize: 13 }}>
                Ask AI to plan my last mile
              </Text>
            </View>
          </Pressable>
        )}

      </ScrollView>
      <PersistentTabBar />
    </View>
  );
}
