/**
 * LastMileCoordinationScreen — dynamic transport options from Firestore.
 * Transport options are generated by Cloud Functions and stored in
 * transport_options/{tripId}_* — loaded via transportStore.
 *
 * REPLACED: My Pickup Preferences → Request Ride button
 * Travelers can now request a ride which appears in operator dashboard.
 */
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState, useEffect, useCallback } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, Share, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { doc, onSnapshot, collection, query, where, limit, setDoc, getDoc, serverTimestamp, deleteDoc, getDocs } from 'firebase/firestore';

import PersistentTabBar from '@/src/components/PersistentTabBar';
import { useAssistantStore } from '@/src/store/assistantStore';
import { useMobilityStore } from '@/src/store/mobilityStore';
import { useTripStore } from '@/src/store/tripStore';
import { useWeatherStore } from '@/src/store/weatherStore';
import { generateShareUpdate, refreshTripMonitoring } from '@/src/firebase/callables';
import { useAuthStore } from '@/src/store/useAuthStore';
import { getFirebaseFirestore } from '@/src/firebase/firebaseApp';
import { createRideRequest, listenToTravelerRideRequests } from '@/src/services/RideRequestService';
import { listenToActiveOperator, getActiveOperator } from '@/src/services/OperatorService';
import type { RideRequestDoc } from '@/src/firebase/lastMileTypes';
import type { TravelerOperatorDoc } from '@/src/firebase/lastMileTypes';
import { SafeText } from '@/src/components/responsive/SafeText';

/* ── Helpers ─────────────────────────────────────────────────────────── */

function fmtDuration(sec: number): string {
  const mins = Math.round(sec / 60);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h ? `${h}h ${m}m` : `${m}m`;
}

const REQUEST_STATUS_META: Record<string, { icon: string; color: string; label: string }> = {
  pending: { icon: 'time', color: '#F59E0B', label: 'Pending — operator reviewing' },
  accepted: { icon: 'checkmark-circle', color: '#3B82F6', label: 'Accepted — driver being assigned' },
  assigned: { icon: 'car', color: '#22C55E', label: 'Assigned — driver on the way' },
  in_progress: { icon: 'navigate', color: '#22C55E', label: 'In Progress' },
  completed: { icon: 'checkmark-done', color: '#64748b', label: 'Completed' },
  cancelled: { icon: 'close-circle', color: '#EF4444', label: 'Cancelled' },
};

/* ── Screen ──────────────────────────────────────────────────────────── */

export default function LastMileCoordinationScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { tripId } = useLocalSearchParams<{ tripId: string }>();
  const uid = useAuthStore((s) => s.token);
  const user = useAuthStore((s) => s.user);
  const [refreshing, setRefreshing] = useState(false);
  const [sharing, setSharing] = useState(false);

  const trips = useTripStore((s) => s.trips);
  const trip = useMemo(
    () => trips.find((t) => String(t.id) === String(tripId)) ?? trips[0] ?? null,
    [tripId, trips],
  );

  const mobility = useMobilityStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const weather = useWeatherStore((s) => trip ? s.byTripId[trip.id] ?? null : null);
  const best = mobility?.bestRoute ?? null;

  const dest = trip?.destinationAirport?.city ?? trip?.to ?? 'destination';

  // ── Active operator ──────────────────────────────────────────────────
  const [activeOperator, setActiveOperator] = useState<(TravelerOperatorDoc & { id: string }) | null>(null);
  const [loadingOperator, setLoadingOperator] = useState(true);

  // ── Ride request state ───────────────────────────────────────────────
  const [rideRequests, setRideRequests] = useState<(RideRequestDoc & { id: string })[]>([]);
  const [submittingRequest, setSubmittingRequest] = useState(false);

  // ── Pickup / dropoff inputs for ride request ─────────────────────────
  const [pickupLocation, setPickupLocation] = useState('');
  const [dropoffLocation, setDropoffLocation] = useState('');
  const [driverNotes, setDriverNotes] = useState('');

  // ── Assignment state ─────────────────────────────────────────────────
  const [assignment, setAssignment] = useState<any>(null);
  const [loadingAssignment, setLoadingAssignment] = useState(false);

  // Load active operator
  useEffect(() => {
    if (!trip?.id || !uid) return;
    setLoadingOperator(true);
    const unsub = listenToActiveOperator(
      uid,
      trip.id,
      (op) => {
        setActiveOperator(op);
        setLoadingOperator(false);
      },
      () => setLoadingOperator(false),
    );
    return () => unsub();
  }, [trip?.id, uid]);

  // Fallback: if no active operator found via listener, try fetching directly
  useEffect(() => {
    if (!trip?.id || !uid || loadingOperator) return;
    let cancelled = false;
    (async () => {
      try {
        const op = await getActiveOperator(uid, trip.id);
        if (!cancelled && op && !activeOperator) {
          setActiveOperator(op);
        }
      } catch { }
    })();
    return () => { cancelled = true; };
  }, [trip?.id, uid, loadingOperator, activeOperator]);

  // Clean up old assignments on mount (client-side only, no delete permission needed)
  useEffect(() => {
    if (!trip?.id || !uid) return;

    // Just clear the local state of any old assignments
    // The server-side filter will handle the rest
    setAssignment(null);
  }, [trip?.id, uid]);

  // Listen to ride requests for this traveler + trip
  useEffect(() => {
    if (!trip?.id || !uid) return;
    const unsub = listenToTravelerRideRequests(
      uid,
      trip.id,
      (requests) => {
        setRideRequests(requests);
      },
    );
    return () => unsub();
  }, [trip?.id, uid]);

  // Listen to assignments for this trip
  useEffect(() => {
    if (!trip?.id || !uid) return;
    setLoadingAssignment(true);
    const db = getFirebaseFirestore();
    const q = query(
      collection(db, 'assignments'),
      where('travelerId', '==', uid),
      where('tripId', '==', trip.id),
      limit(1),
    );
    const unsub = onSnapshot(
      q,
      async (snap) => {
        if (!snap.empty) {
          const assignmentData = { id: snap.docs[0].id, ...snap.docs[0].data() };
          const assignmentStatus = (assignmentData as any)?.status?.toLowerCase() || '';

          // Only show if assignment is active (not completed/cancelled)
          const isActive = ['assigned', 'in_progress', 'ride_started', 'started', 'driver_arrived', 'near_destination'].includes(assignmentStatus);

          if (isActive) {
            // Check ride request if present - web portal assignments may not have rideRequestId
            const rideRequestId = (assignmentData as any).rideRequestId;
            if (rideRequestId) {
              try {
                const rideReqDoc = await getDoc(doc(db, 'rideRequests', rideRequestId));
                if (rideReqDoc.exists()) {
                  const rideReqData = rideReqDoc.data();
                  const rideStatus = (rideReqData as any)?.status?.toLowerCase() || '';
                  const isRideActive = !['completed', 'cancelled', 'canceled'].includes(rideStatus);

                  if (isRideActive) {
                    setAssignment(assignmentData);
                  } else {
                    setAssignment(null);
                  }
                } else {
                  setAssignment(null);
                }
              } catch {
                setAssignment(null);
              }
            } else {
              // No rideRequestId - assignment was created directly from web portal
              // Show it anyway since it's an active assignment
              setAssignment(assignmentData);
            }
          } else {
            setAssignment(null);
          }
        } else {
          setAssignment(null);
        }
        setLoadingAssignment(false);
      },
      () => setLoadingAssignment(false),
    );
    return () => unsub();
  }, [trip?.id, uid]);

  // Load existing pickup preferences from Firestore
  useEffect(() => {
    if (!trip?.id || !uid) return;
    const db = getFirebaseFirestore();
    const prefsRef = doc(db, 'tripPickupPreferences', trip.id);
    getDoc(prefsRef)
      .then((snap) => {
        if (snap.exists()) {
          const data = snap.data();
          setPickupLocation(data.pickupLocation || '');
          setDropoffLocation(data.dropoffLocation || '');
          setDriverNotes(data.driverNotes || '');
        }
      })
      .catch(() => { });
  }, [trip?.id, uid]);

  // ── Handle ride request ─────────────────────────────────────────────
  const handleRequestRide = useCallback(async () => {
    if (!activeOperator || !uid || !trip?.id) {
      Alert.alert(
        'No Operator Selected',
        'Please select an operator first to request a ride.',
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Select Operator',
            onPress: () => router.push({ pathname: '/operator/select' as any, params: { tripId: trip?.id } } as any),
          },
        ],
      );
      return;
    }

    if (!pickupLocation.trim()) {
      Alert.alert('Pickup Required', 'Please enter your preferred pickup location.');
      return;
    }

    setSubmittingRequest(true);
    try {
      const requestId = await createRideRequest(
        uid,
        activeOperator.operatorId,
        trip.id,
        pickupLocation.trim(),
        undefined,
        undefined,
        dropoffLocation.trim() || dest,
        undefined,
        undefined,
        driverNotes.trim(),
        user?.name || user?.email || undefined,
      );

      // Also save as pickup preferences for the driver
      const db = getFirebaseFirestore();
      await setDoc(doc(db, 'tripPickupPreferences', trip.id), {
        tripId: trip.id,
        travelerId: uid,
        pickupLocation: pickupLocation.trim(),
        dropoffLocation: dropoffLocation.trim(),
        driverNotes: driverNotes.trim(),
        rideRequestId: requestId,
        updatedAt: serverTimestamp(),
      }).catch(() => { });

      Alert.alert(
        'Ride Requested',
        `Your ride request has been sent to ${activeOperator.operatorName || 'your operator'}. They will review and assign a driver shortly.`,
      );
    } catch (e: any) {
      Alert.alert('Request Failed', e?.message || 'Failed to submit ride request. Please try again.');
    } finally {
      setSubmittingRequest(false);
    }
  }, [activeOperator, uid, trip, pickupLocation, dropoffLocation, driverNotes, dest, router, user]);

  // ── Existing handlers ────────────────────────────────────────────────
  async function handleRefresh() {
    if (!trip || !uid || refreshing) return;
    setRefreshing(true);
    try {
      await refreshTripMonitoring(trip.id);
    } catch (e: any) {
      if (e?.message === 'Unavailable' || e?.code === 'unavailable') {
        Alert.alert('Refresh limited', 'Could not reach server. Showing cached data.');
      } else {
        Alert.alert('Refresh failed', e?.message ?? 'Please try again.');
      }
    } finally {
      setRefreshing(false);
    }
  }

  async function handleShare() {
    if (!trip) return;
    setSharing(true);
    try {
      const { shareText } = await generateShareUpdate(trip.id);
      await Share.share({ message: shareText, title: trip.title });
    } catch {
      const fallback = [`📍 ${trip?.title || 'Trip'}`, `From: ${trip?.from || 'Origin'} → To: ${trip?.to || 'Destination'}`, '', 'Powered by TICS'].filter(Boolean).join('\n');
      await Share.share({ message: fallback, title: trip?.title ?? 'TICS Trip' }).catch(() => { });
    } finally {
      setSharing(false);
    }
  }

  const handleCallDriver = async () => {
    if (!assignment?.driverPhone) {
      Alert.alert('Error', 'Driver phone number not available');
      return;
    }
    const phone = assignment.driverPhone.startsWith('0')
      ? `256${assignment.driverPhone.substring(1)}`
      : assignment.driverPhone;
    const url = `tel:${phone}`;
    const supported = await Linking.canOpenURL(url);
    if (supported) {
      await Linking.openURL(url);
    } else {
      Alert.alert('Error', 'Unable to open phone dialer');
    }
  };

  const handleWhatsAppDriver = async () => {
    if (!assignment?.driverPhone) {
      Alert.alert('Error', 'Driver phone number not available');
      return;
    }
    const phone = assignment.driverPhone.replace(/[^\d]/g, '');
    let extraContext = '';
    if (pickupLocation) extraContext += `\nPickup: ${pickupLocation}`;
    if (dropoffLocation) extraContext += `\nDropoff: ${dropoffLocation}`;
    if (driverNotes) extraContext += `\nNotes: ${driverNotes}`;
    const message = encodeURIComponent(`Hello ${assignment.driverName}, I am your assigned traveler.${extraContext}`);
    const whatsappUrl = `whatsapp://send?phone=${phone}&text=${message}`;
    const supported = await Linking.canOpenURL(whatsappUrl);
    if (supported) {
      await Linking.openURL(whatsappUrl);
    } else {
      Alert.alert('WhatsApp Not Installed', 'Please install WhatsApp to contact the driver.');
    }
  };

  // Determine the latest ride request status
  const latestRequest = rideRequests.length > 0 ? rideRequests[0] : null;
  const hasPendingRequest = latestRequest && ['pending', 'accepted'].includes(latestRequest.status);
  const hasAssignedRide = latestRequest && ['assigned', 'in_progress', 'ride_started', 'started'].includes(latestRequest.status);
  const isRideCompleted = latestRequest && ['completed', 'cancelled', 'canceled'].includes(latestRequest.status);

  // Show driver card only if there's an assignment with active status AND ride is not completed/cancelled
  const assignmentStatus = (assignment as any)?.status?.toLowerCase() || '';
  const isAssignmentActive = ['assigned', 'in_progress', 'ride_started', 'started', 'driver_arrived', 'near_destination'].includes(assignmentStatus);

  // Hide driver card if ride request is completed/cancelled
  const shouldHideDriverCard = isRideCompleted;

  // Final check: only show driver card if ALL conditions are met
  const effectiveShowDriverCard = !shouldHideDriverCard && !!assignment && isAssignmentActive;

  // Show "Request a Ride" button only when there's NO assignment AND no pending/assigned ride request
  const canRequestNewRide = !assignment && !hasPendingRequest && !hasAssignedRide;

  // Debug logging
  console.log('[Coordination] Debug:', {
    hasAssignment: !!assignment,
    assignmentStatus: (assignment as any)?.status,
    rideRequestsCount: rideRequests.length,
    latestRequestStatus: latestRequest?.status,
    hasPendingRequest,
    hasAssignedRide,
    isRideCompleted,
    canRequestNewRide,
    activeOperator: !!activeOperator,
  });

  // Safety: Clear assignment when ride is completed/cancelled
  useEffect(() => {
    if (isRideCompleted && assignment) {
      setAssignment(null);
    }
  }, [isRideCompleted, assignment]);

  return (
    <View className="flex-1 p-1">
      {/* Header */}
      <View className="p-2 mb-4 flex-row items-center gap-3 bg-tics-amber/25 border border-tics-amber/10 rounded-full">
        <View style={{ flexDirection: 'row', gap: 8 }}>
          <Pressable
            onPress={() => router.back()}
            className="bg-tics-amber/35 border border-tics-amber/20 rounded-full"
            style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
          >
            <Ionicons name="chevron-back" size={20} color="rgba(248,250,252,0.9)" />
          </Pressable>
          <View className="border border-tics-purple rounded-full" style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}>
            <Ionicons name="car" size={18} color="#8B5CF6" />
          </View>
        </View>
        <View style={{ flex: 1 }}>
          <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#f8fafc', fontSize: 17 }}>Last-Mile</SafeText>
          <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 11 }} numberOfLines={1}>
            {trip?.title ?? 'Ground transport'}
          </SafeText>
        </View>
        <Pressable
          onPress={handleShare}
          disabled={sharing}
          className="bg-tics-amber/35 border border-tics-amber/20 rounded-full"
          style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
        >
          {sharing ? <ActivityIndicator size={14} color="#fff" /> : <Ionicons name="share-social-outline" size={17} color="#fff" />}
        </Pressable>
        <Pressable
          onPress={handleRefresh}
          disabled={refreshing}
          style={{ width: 46, height: 46, alignItems: 'center', justifyContent: 'center' }}
          className="rounded-full bg-tics-amber/35 border border-tics-amber/20"
        >
          {refreshing ? <ActivityIndicator size={14} color="#fff" /> : <Ionicons name="refresh" size={17} color="#fff" />}
        </Pressable>
      </View>

      <ScrollView
        className='px-1'
        contentContainerStyle={{ gap: 14, paddingBottom: 13 }}
        showsVerticalScrollIndicator={false}>
        {/* Route summary */}
        <View className="rounded-4xl bg-tics-amber/25 border border-tics-amber/10" style={{ padding: 20 }}>
          <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#A78BFA', fontSize: 11, letterSpacing: 0.8, marginBottom: 12 }}>
            ROUTE COORDINATION
          </SafeText>
          <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#f8fafc', fontSize: 16 }}>
            {trip?.to ? `Arriving at ${dest}` : 'Add a trip to enable last-mile coordination'}
          </SafeText>

          {/* Best route */}
          <View className="my-5">
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#A78BFA', fontSize: 10, letterSpacing: 0.8, marginBottom: 6 }}>
              COMPUTED ROUTE
            </SafeText>
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#f8fafc', fontSize: 14 }}>
              {best ? `${fmtDuration(best.durationSec)} · ${(best.distanceMeters / 1000).toFixed(1)} km` : 'Route computed after destination coordinates are set'}
            </SafeText>
            {mobility?.origin?.label && mobility?.destination?.label && (
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12, marginTop: 4 }}>
                {mobility.origin.label} → {mobility.destination.label}
              </SafeText>
            )}
          </View>

          {/* Weather */}
          {weather && weather.tempC != null && (
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              <Ionicons name="partly-sunny" size={16} color="#FBBF24" />
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12 }}>
                {dest}: {Math.round(weather.tempC)}°C, {weather.description ?? 'conditions unknown'}
                {weather.riskScore >= 3 ? ' — allow extra travel time' : ''}
              </SafeText>
            </View>
          )}

          {/* Action buttons */}
          <View className="w-full" style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
            <Pressable
              onPress={() => trip && router.push({ pathname: `/trips/${trip.id}/map` } as any)}
              className="bg-tics-amber/35 border border-tics-amber/20 items-center justify-center p-6 text-sm rounded-full flex-1"
            >
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff' }}>View map</SafeText>
            </Pressable>
            <Pressable
              onPress={handleShare}
              disabled={sharing}
              className="bg-white/[0.05] border border-tics-amber/50 items-center justify-center p-6 text-sm rounded-full flex-1"
            >
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff' }}>Share update</SafeText>
            </Pressable>
          </View>
        </View>

        {/* ── Operator Status ─────────────────────────────────────────── */}
        {loadingOperator ? (
          <View className="rounded-full" style={{ padding: 20, alignItems: 'center', backgroundColor: 'rgba(59,130,246,0.06)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.12)' }}>
            <ActivityIndicator size="small" color="#60A5FA" />
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12, marginTop: 6 }}>Loading operator info...</SafeText>
          </View>
        ) : activeOperator ? (
          <View className="rounded-full border border-tics-amber/30 bg-white/[0.05]" style={{ padding: 16 }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
              <View style={{ width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(34,197,94,0.2)', alignItems: 'center', justifyContent: 'center' }}>
                <Ionicons name="business" size={20} color="#22C55E" />
              </View>
              <View style={{ flex: 1 }}>
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#22C55E', fontSize: 13 }}>
                  {activeOperator.operatorName || 'Operator'}
                </SafeText>
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 11, marginTop: 2 }}>
                  Managing your rides this trip
                </SafeText>
              </View>
              <Pressable
                onPress={() => {
                  const operatorId = activeOperator?.operatorId || assignment?.operatorId;
                  if (!operatorId) {
                    Alert.alert('No Operator', 'Please select an operator first');
                    return;
                  }
                  router.push({
                    pathname: '/last-mile/operator-details' as any,
                    params: { operatorId, tripId: trip?.id } as any
                  } as any);
                }}
                className="rounded-full bg-tics-amber/35 border border-tics-amber/20"
                style={{ paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1, }}
              >
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#60A5FA', fontSize: 11 }}>Contact</SafeText>
              </Pressable>
            </View>
          </View>
        ) : (
          <View className="rounded-4xl" style={{ padding: 16, alignItems: 'center', backgroundColor: 'rgba(139,92,246,0.20)', borderWidth: 1, borderColor: 'rgba(139,92,246,0.10)' }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              <Ionicons name="alert-circle" size={18} color="#F59E0B" />
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#F59E0B', fontSize: 13 }}>No operator selected</SafeText>
            </View>
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 11, marginTop: 4, textAlign: 'center' }}>
              Select an operator to request a ride
            </SafeText>
            <Pressable
              onPress={() => router.push({ pathname: '/operator/select' as any, params: { tripId: trip?.id } } as any)}
              className="rounded-full mt-3 p-6 w-full items-center bg-tics-amber/35 border border-tics-amber/20"
            >
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 12 }}>Select Operator</SafeText>
            </Pressable>
          </View>
        )}

        {/* ── REQUEST A RIDE BUTTON ──── */}
        {/* Show button when there's no active assignment */}
        {canRequestNewRide && (
          <Pressable
            onPress={() => {
              if (!activeOperator) {
                Alert.alert(
                  'No Operator Selected',
                  'Please select an operator first to request a ride.',
                  [
                    { text: 'Cancel', style: 'cancel' },
                    { text: 'Select Operator', onPress: () => router.push({ pathname: '/operator/select' as any, params: { tripId: trip?.id } } as any) },
                  ],
                );
                return;
              }
              router.push({
                pathname: '/last-mile/destination-select' as any,
                params: {
                  assignmentId: '',
                  tripId: trip?.id,
                  operatorId: activeOperator.operatorId,
                  operatorName: activeOperator.operatorName,
                },
              } as any);
            }}
            className="rounded-full flex-row gap-3 items-center p-2 bg-tics-amber/25 border border-tics-amber/10"
          >
            <View style={{ width: 46, height: 46 }} className='bg-tics-amber/35 border border-tics-amber/20 items-center justify-center rounded-full'>
              <Ionicons name="car-sport" size={24} color="#fff" />
            </View>
            <View>
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 17 }}>
                Request a Ride
              </SafeText>
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: 'rgba(255,255,255,0.6)', fontSize: 11, marginTop: 2 }}>
                {activeOperator ? `via ${activeOperator.operatorName || 'your operator'}` : 'Select an operator first'}
              </SafeText>
            </View>
          </Pressable>
        )}

        {/* ── Assignment / Driver Assigned - Full driver card ── */}
        {loadingAssignment ? (
          <View className="rounded-4xl" style={{ padding: 20, backgroundColor: 'rgba(59,130,246,0.08)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.15)', alignItems: 'center' }}>
            <ActivityIndicator size="small" color="#60A5FA" />
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12, marginTop: 8 }}>Loading pickup details...</SafeText>
          </View>
        ) : effectiveShowDriverCard && assignment ? (
          <View className="rounded-4xl bg-tics-amber/25 border border-tics-amber/10" style={{ padding: 16 }}>
            {/* Driver info header */}
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 }}>
              <View className="rounded-full" style={{ width: 48, height: 48, backgroundColor: 'rgba(34,197,94,0.25)', alignItems: 'center', justifyContent: 'center' }}>
                <Ionicons name="car" size={24} color="#22C55E" />
              </View>
              <View style={{ flex: 1 }}>
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#22C55E', fontSize: 16 }}>
                  {assignment.driverName || 'Driver assigned'}
                </SafeText>
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12, marginTop: 2 }}>
                  {assignment.vehicle || ''} {assignment.plateNumber ? `(${assignment.plateNumber})` : ''}
                </SafeText>
              </View>
            </View>

            {/* Driver details */}
            <View style={{ gap: 8, marginBottom: 14 }}>
              {assignment.driverPhone && (
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Ionicons name="call" size={16} color="#60A5FA" />
                  <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#e2e8f0', fontSize: 13 }}>{assignment.driverPhone}</SafeText>
                </View>
              )}
              {assignment.pickupLocation && (
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Ionicons name="location" size={16} color="#60A5FA" />
                  <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#e2e8f0', fontSize: 13 }}>{assignment.pickupLocation}</SafeText>
                </View>
              )}
              {assignment.eta && (
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                  <Ionicons name="time" size={16} color="#60A5FA" />
                  <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#e2e8f0', fontSize: 13 }}>
                    ETA: {new Date(assignment.eta).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hour12: true })}
                  </SafeText>
                </View>
              )}
            </View>

            {/* Contact buttons */}
            <View style={{ flexDirection: 'row', gap: 10, marginBottom: 12 }}>
              {assignment.driverPhone && (
                <Pressable
                  onPress={handleCallDriver}
                  className="flex-1 flex-row items-center justify-center gap-2 rounded-full p-4"
                  style={{ backgroundColor: 'rgba(59,130,246,0.15)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.2)' }}
                >
                  <Ionicons name="call" size={18} color="#fff" />
                  <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 11, marginTop: 4 }}>Call</SafeText>
                </Pressable>
              )}
              <Pressable
                onPress={handleWhatsAppDriver}
                className="flex-1 flex-row items-center justify-center gap-2 rounded-full p-4"
                style={{ backgroundColor: 'rgba(59,130,246,0.15)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.2)' }}
              >
                <Ionicons name="logo-whatsapp" size={18} color="#fff" />
                <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 11, marginTop: 4 }}>WhatsApp</SafeText>
              </Pressable>
            </View>

            {/* View tracking map button */}
            <Pressable
              onPress={() => {
                const aId = assignment?.id || '';
                const tId = trip?.id || '';
                router.push({
                  pathname: '/last-mile/tracking' as any,
                  params: {
                    assignmentId: aId,
                    tripId: tId,
                    driverArrived: 'true'
                  }
                } as any);
              }}
              className="rounded-full gap-3 flex-row p-6 bg-tics-amber/35 border border-tics-amber/20"
              style={{ alignItems: 'center', justifyContent: 'center' }}
            >
              <Ionicons name="map" size={18} color="#fff" />
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 14, marginTop: 4 }}>
                View Tracking Map
              </SafeText>
            </Pressable>
          </View>
        ) : !canRequestNewRide && !isRideCompleted && !hasPendingRequest && !hasAssignedRide && (
          <View className="bg-tics-amber/25 border border-tics-amber/10 rounded-4xl" style={{ padding: 20, alignItems: 'center', gap: 10 }}>
            <Ionicons name="car-outline" size={32} color="rgba(248,250,252,0.15)" />
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 13 }}>No pickup assigned yet</SafeText>
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#64748b', fontSize: 11, textAlign: 'center', lineHeight: 16 }}>
              Request a ride above and an operator will assign a driver.
            </SafeText>
          </View>
        )}

        {/* ── Ride Completed/Cancelled - Show summary and allow new request ── */}
        {isRideCompleted && (
          <View className="bg-tics-amber/25 border border-tics-amber/10 rounded-4xl" style={{ padding: 20, alignItems: 'center', gap: 10 }}>
            <Ionicons
              name={latestRequest.status === 'completed' ? 'checkmark-circle' : 'close-circle'}
              size={40}
              color={latestRequest.status === 'completed' ? '#22C55E' : '#EF4444'}
            />
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#f8fafc', fontSize: 16 }}>
              Ride {latestRequest.status === 'completed' ? 'Completed' : 'Cancelled'}
            </SafeText>
            <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#94a3b8', fontSize: 12, textAlign: 'center', lineHeight: 18 }}>
              Your ride from {latestRequest.pickupLocation} to {latestRequest.destination} has been {latestRequest.status}.
            </SafeText>
            <Pressable
              onPress={() => {
                // Clear the completed request to allow new ride request
                setRideRequests([]);
                setAssignment(null);
              }}
              className="rounded-full mt-2 p-4 w-full items-center bg-tics-amber/35 border border-tics-amber/20"
            >
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 13 }}>
                Request New Ride
              </SafeText>
            </Pressable>
          </View>
        )}

        {/* Ask AI */}
        {trip && (
          <Pressable
            onPress={() => {
              const msg = `[Last Mile Planning]\nI'm arriving at ${dest}${trip.flightNumber ? ` on flight ${trip.flightNumber}` : ''}${trip.arrivalTime ? ` at ${new Date(trip.arrivalTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : ''}. The weather at destination is ${weather ? `${Math.round(weather.tempC ?? 0)}°C, ${weather.description ?? 'unknown'}` : 'unknown'}.\n\nPlease help me plan my last mile:\n1. What's the best transport option from ${dest} airport?\n2. Estimated costs and travel times\n3. How to book or arrange pickup\n4. Any tips for navigating the airport arrival area`;
              useAssistantStore.getState().setPendingMessage(msg, trip.id);
              router.push('/assistant' as any);
            }}
          >
            <View className="bg-tics-amber/35 border border-tics-amber/20 rounded-full p-6" style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
              <Ionicons name="sparkles-outline" size={18} color="#fff" />
              <SafeText style={{ fontFamily: 'ShareTech_400Regular', color: '#fff', fontSize: 13 }}>Ask AI to plan my last mile</SafeText>
            </View>
          </Pressable>
        )}
      </ScrollView>
      <PersistentTabBar />
    </View>
  );
}
