/**
 * seedDestinations.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Seeds the Firestore `destinations` collection with metadata for common
 * travel destinations. Run this once to populate initial data.
 *
 * Usage: npx ts-node -e "require('./src/scripts/seedDestinations').run()"
 * Or import and call seedDestinations() from your admin tooling.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { seedDestinations, type DestinationMetadata } from '../services/DestinationsService';

const SEED_DATA: DestinationMetadata[] = [
  // ── Europe ────────────────────────────────────────────────────────────
  {
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    description: 'The City of Light — world capital of art, fashion, gastronomy, and culture. From the Eiffel Tower to hidden bistros, every corner tells a story.',
    travelTips: [
      'Book museum tickets online in advance to skip queues at the Louvre.',
      'Learn a few French phrases; locals appreciate the effort.',
      'Visit Montmartre early morning to avoid crowds.',
      'Get a Navigo card for unlimited metro travel.',
    ],
    bestTimeToVisit: 'April–June & September–October for mild weather and fewer crowds.',
    currency: 'Euro (€)',
    language: 'French',
    timezone: 'CET (UTC+1)',
    topAttractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral', 'Sacré-Cœur Basilica', 'Palace of Versailles', 'Musée d\'Orsay', 'Luxembourg Gardens'],
    travelCategories: ['culture', 'romantic', 'food', 'art', 'history', 'shopping'],
    estimatedBudget: { min: 1500, max: 5000, currency: 'EUR' },
    lat: 48.8566,
    lng: 2.3522,
    updatedAt: null as any,
  },
  {
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    description: 'A city steeped in history, from royal palaces and world-class museums to a thriving arts and food scene.',
    travelTips: [
      'Use an Oyster card for the cheapest Tube fares.',
      'Many top museums like the British Museum are free.',
      'Book theatre tickets in advance for best prices.',
      'Walk along the South Bank for iconic river views.',
    ],
    bestTimeToVisit: 'March–May & September–November for mild weather and fewer tourists.',
    currency: 'Pound Sterling (£)',
    language: 'English',
    timezone: 'GMT (UTC+0)',
    topAttractions: ['Big Ben', 'Tower of London', 'Buckingham Palace', 'British Museum', 'London Eye', 'Tower Bridge', 'Hyde Park'],
    travelCategories: ['culture', 'history', 'shopping', 'food', 'business'],
    estimatedBudget: { min: 1200, max: 4000, currency: 'GBP' },
    lat: 51.5074,
    lng: -0.1278,
    updatedAt: null as any,
  },
  {
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    description: 'The Eternal City — a living museum of ancient ruins, Renaissance art, and incredible Italian cuisine.',
    travelTips: [
      'Book Colosseum tickets weeks in advance.',
      'Visit the Vatican Museum on Friday evenings for fewer crowds.',
      'Toss a coin in Trevi Fountain for good luck.',
      'Stay in Trastevere for authentic Roman evenings.',
    ],
    bestTimeToVisit: 'April–June & September–October for pleasant walking weather.',
    currency: 'Euro (€)',
    language: 'Italian',
    timezone: 'CET (UTC+1)',
    topAttractions: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Roman Forum', 'Pantheon', 'Spanish Steps', 'Galleria Borghese'],
    travelCategories: ['history', 'culture', 'food', 'romantic', 'art'],
    estimatedBudget: { min: 1000, max: 3500, currency: 'EUR' },
    lat: 41.9028,
    lng: 12.4964,
    updatedAt: null as any,
  },
  {
    name: 'Santorini',
    country: 'Greece',
    countryCode: 'GR',
    description: 'A stunning Greek island famous for its blue-domed churches, white-washed buildings, and volcanic sunsets.',
    travelTips: [
      'Stay in Fira or Imerovigli for more affordable caldera views.',
      'Book sunset dinner spots weeks in advance.',
      'Rent an ATV to explore the island.',
      'Visit in shoulder season (May/Sept) for pleasant weather.',
    ],
    bestTimeToVisit: 'June–September for warm weather and sunset views.',
    currency: 'Euro (€)',
    language: 'Greek',
    timezone: 'EET (UTC+2)',
    topAttractions: ['Oia Sunset Viewpoint', 'Red Beach', 'Fira Town', 'Akrotiri Ruins', 'Wine Tasting Tours', 'Amoudi Bay'],
    travelCategories: ['beach', 'romantic', 'food', 'culture', 'photography'],
    estimatedBudget: { min: 1200, max: 4000, currency: 'EUR' },
    lat: 36.3932,
    lng: 25.4615,
    updatedAt: null as any,
  },
  {
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    description: 'A vibrant Mediterranean city blending Gothic architecture with modernist masterpieces by Gaudí.',
    travelTips: [
      'Book Sagrada Familia tickets months in advance.',
      'Explore the Gothic Quarter on foot.',
      'Try authentic paella by the beach.',
      'Use the metro — it\'s efficient and affordable.',
    ],
    bestTimeToVisit: 'May–June & September–October for warm weather without peak crowds.',
    currency: 'Euro (€)',
    language: 'Spanish, Catalan',
    timezone: 'CET (UTC+1)',
    topAttractions: ['Sagrada Familia', 'Park Güell', 'La Rambla', 'Gothic Quarter', 'Casa Batlló', 'Barceloneta Beach'],
    travelCategories: ['beach', 'culture', 'food', 'art', 'nightlife'],
    estimatedBudget: { min: 800, max: 3000, currency: 'EUR' },
    lat: 41.3874,
    lng: 2.1686,
    updatedAt: null as any,
  },

  // ── Asia ──────────────────────────────────────────────────────────────
  {
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    description: 'A dazzling blend of ultramodern and traditional — neon-lit skyscrapers meet ancient temples in this vibrant metropolis.',
    travelTips: [
      'Get a Suica or Pasmo card for seamless train travel.',
      'Visit Tsukiji Outer Market for fresh sushi.',
      'Learn basic Japanese phrases for a better experience.',
      'Use Google Maps for navigating the complex train system.',
    ],
    bestTimeToVisit: 'March–May for cherry blossoms or October–November for autumn colors.',
    currency: 'Japanese Yen (¥)',
    language: 'Japanese',
    timezone: 'JST (UTC+9)',
    topAttractions: ['Shibuya Crossing', 'Senso-ji Temple', 'Tokyo Skytree', 'Meiji Shrine', 'Akihabara Electric Town', 'Shinjuku Gyoen'],
    travelCategories: ['culture', 'food', 'technology', 'shopping', 'history'],
    estimatedBudget: { min: 1500, max: 5000, currency: 'USD' },
    lat: 35.6762,
    lng: 139.6503,
    updatedAt: null as any,
  },
  {
    name: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    description: 'The Island of the Gods — lush rice terraces, ancient temples, vibrant arts, and world-class surf breaks.',
    travelTips: [
      'Rent a scooter for the most authentic way to explore.',
      'Always carry cash — many places don\'t accept cards.',
      'Visit temples respectfully with sarongs.',
      'Stay in Ubud for culture, Seminyak for nightlife.',
    ],
    bestTimeToVisit: 'April–October (dry season) for sunny days and calm seas.',
    currency: 'Indonesian Rupiah (IDR)',
    language: 'Indonesian / Balinese',
    timezone: 'WITA (UTC+8)',
    topAttractions: ['Tegallalang Rice Terraces', 'Uluwatu Temple', 'Ubud Monkey Forest', 'Tanah Lot Temple', 'Mount Batur Sunrise Trek', 'Seminyak Beach'],
    travelCategories: ['beach', 'culture', 'spa', 'nature', 'yoga', 'surf'],
    estimatedBudget: { min: 500, max: 2000, currency: 'USD' },
    lat: -8.3405,
    lng: 115.0920,
    updatedAt: null as any,
  },
  {
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    description: 'A futuristic city-state where Chinese, Malay, and Indian cultures blend with stunning modern architecture.',
    travelTips: [
      'Hawker centers offer the best and cheapest local food.',
      'The MRT is efficient and covers the whole island.',
      'Respect strict laws — no chewing gum, strict littering fines.',
      'Visit Gardens by the Bay at sunset for magical views.',
    ],
    bestTimeToVisit: 'February–April for the driest weather.',
    currency: 'Singapore Dollar (SGD)',
    language: 'English, Mandarin, Malay, Tamil',
    timezone: 'SGT (UTC+8)',
    topAttractions: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Chinatown', 'Little India', 'Orchard Road'],
    travelCategories: ['business', 'food', 'shopping', 'culture', 'modern'],
    estimatedBudget: { min: 1000, max: 4000, currency: 'SGD' },
    lat: 1.3521,
    lng: 103.8198,
    updatedAt: null as any,
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    description: 'A futuristic oasis in the desert — home to the world\'s tallest building, luxury shopping, and breathtaking architecture.',
    travelTips: [
      'Visit the Dubai Miracle Garden from November to May.',
      'Book Burj Khalifa tickets online for sunset slots.',
      'Dress modestly in public areas.',
      'Use the metro to avoid traffic jams.',
    ],
    bestTimeToVisit: 'November–March when temperatures are mild (20–30°C).',
    currency: 'UAE Dirham (AED)',
    language: 'Arabic',
    timezone: 'GST (UTC+4)',
    topAttractions: ['Burj Khalifa', 'Palm Jumeirah', 'Dubai Mall', 'Burj Al Arab', 'Dubai Desert Safari', 'Dubai Marina'],
    travelCategories: ['luxury', 'shopping', 'business', 'food', 'modern'],
    estimatedBudget: { min: 1500, max: 8000, currency: 'USD' },
    lat: 25.2048,
    lng: 55.2708,
    updatedAt: null as any,
  },

  // ── Africa ─────────────────────────────────────────────────────────────
  {
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    description: 'The Green City in the Sun — Kenya\'s vibrant capital, gateway to East African safaris, and a hub of innovation and culture.',
    travelTips: [
      'Visit the Giraffe Centre early morning for fewer crowds.',
      'Use ride-hailing apps like Uber or Bolt for safe transport.',
      'Try nyama choma at a local carnivore restaurant.',
      'Book safari trips through reputable operators.',
    ],
    bestTimeToVisit: 'June–October & January–February for wildlife viewing.',
    currency: 'Kenyan Shilling (KES)',
    language: 'Swahili / English',
    timezone: 'EAT (UTC+3)',
    topAttractions: ['Nairobi National Park', 'Elephant Orphanage', 'Giraffe Centre', 'Karen Blixen Museum', 'Nairobi National Museum', 'Bomas of Kenya'],
    travelCategories: ['safari', 'culture', 'nature', 'business', 'history'],
    estimatedBudget: { min: 500, max: 2000, currency: 'USD' },
    lat: -1.2921,
    lng: 36.8219,
    updatedAt: null as any,
  },
  {
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    description: 'Where the Atlantic meets the Indian Ocean — stunning beaches, iconic Table Mountain, and a vibrant cultural melting pot.',
    travelTips: [
      'Take the aerial cableway up Table Mountain — check weather first.',
      'Visit Boulders Beach for the penguin colony.',
      'Drive the Chapman\'s Peak route for stunning coastal views.',
      'Explore the V&A Waterfront for shopping and dining.',
    ],
    bestTimeToVisit: 'November–March (summer) for warm, sunny days.',
    currency: 'South African Rand (ZAR)',
    language: '11 official languages including Zulu, Xhosa, Afrikaans, English',
    timezone: 'SAST (UTC+2)',
    topAttractions: ['Table Mountain', 'Cape of Good Hope', 'Boulders Beach Penguins', 'V&A Waterfront', 'Robben Island', 'Kirstenbosch Botanical Garden'],
    travelCategories: ['nature', 'beach', 'culture', 'wine', 'adventure'],
    estimatedBudget: { min: 600, max: 2500, currency: 'USD' },
    lat: -33.9249,
    lng: 18.4241,
    updatedAt: null as any,
  },
  {
    name: 'Zanzibar',
    country: 'Tanzania',
    countryCode: 'TZ',
    description: 'A tropical paradise of white-sand beaches, turquoise waters, and rich Swahili culture and history.',
    travelTips: [
      'Stay in Nungwi for beautiful beaches, Stone Town for culture.',
      'Take a spice tour — Zanzibar is the Spice Island.',
      'Try fresh seafood at Forodhani Night Market.',
      'Respect local customs; dress modestly in Stone Town.',
    ],
    bestTimeToVisit: 'June–October & January–March for dry, sunny weather.',
    currency: 'Tanzanian Shilling (TZS)',
    language: 'Swahili / English',
    timezone: 'EAT (UTC+3)',
    topAttractions: ['Stone Town', 'Nungwi Beach', 'Prison Island', 'Spice Plantations', 'Jozani Forest', 'Mnemba Island'],
    travelCategories: ['beach', 'culture', 'history', 'diving', 'spice'],
    estimatedBudget: { min: 500, max: 2000, currency: 'USD' },
    lat: -6.1659,
    lng: 39.2026,
    updatedAt: null as any,
  },
  {
    name: 'Marrakech',
    country: 'Morocco',
    countryCode: 'MA',
    description: 'A sensory feast of vibrant souks, stunning palaces, and the gateway to the Sahara Desert.',
    travelTips: [
      'Haggle respectfully in the souks — it\'s expected.',
      'Stay in a traditional riad for an authentic experience.',
      'Try tagine and mint tea at a local cafe.',
      'Book a guided tour of the medina to get your bearings.',
    ],
    bestTimeToVisit: 'March–May & September–November for pleasant temperatures.',
    currency: 'Moroccan Dirham (MAD)',
    language: 'Arabic / Berber / French',
    timezone: 'WET (UTC+0)',
    topAttractions: ['Jemaa el-Fnaa', 'Bahia Palace', 'Koutoubia Mosque', 'Majorelle Garden', 'Souks of Marrakech', 'Atlas Mountains'],
    travelCategories: ['culture', 'food', 'shopping', 'history', 'desert'],
    estimatedBudget: { min: 400, max: 1500, currency: 'USD' },
    lat: 31.6295,
    lng: -7.9811,
    updatedAt: null as any,
  },

  // ── Americas ───────────────────────────────────────────────────────────
  {
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    description: 'The city that never sleeps — a global hub for finance, culture, entertainment, and world-class dining.',
    travelTips: [
      'Get a MetroCard or OMNY for unlimited 7-day subway access.',
      'Book Broadway tickets in advance for best prices.',
      'Visit Central Park early morning for a peaceful experience.',
      'Walk the High Line for unique city views.',
    ],
    bestTimeToVisit: 'April–June & September–November for pleasant weather.',
    currency: 'US Dollar ($)',
    language: 'English',
    timezone: 'EST (UTC-5)',
    topAttractions: ['Statue of Liberty', 'Times Square', 'Central Park', 'Empire State Building', 'Broadway', 'Brooklyn Bridge', 'Metropolitan Museum of Art'],
    travelCategories: ['business', 'culture', 'food', 'shopping', 'art', 'theatre'],
    estimatedBudget: { min: 2000, max: 7000, currency: 'USD' },
    lat: 40.7128,
    lng: -74.0060,
    updatedAt: null as any,
  },
  {
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    description: 'A vibrant city of stunning beaches, dramatic mountains, and infectious samba rhythms.',
    travelTips: [
      'Stay in Copacabana or Ipanema for beach access.',
      'Take the cog train up to Christ the Redeemer early.',
      'Learn basic Portuguese for a better experience.',
      'Use Uber for safer transportation.',
    ],
    bestTimeToVisit: 'December–March for summer weather and festivals.',
    currency: 'Brazilian Real (BRL)',
    language: 'Portuguese',
    timezone: 'BRT (UTC-3)',
    topAttractions: ['Christ the Redeemer', 'Sugarloaf Mountain', 'Copacabana Beach', 'Ipanema Beach', 'Maracanã Stadium', 'Lapa Arches'],
    travelCategories: ['beach', 'culture', 'music', 'nature', 'festival'],
    estimatedBudget: { min: 800, max: 3000, currency: 'USD' },
    lat: -22.9068,
    lng: -43.1729,
    updatedAt: null as any,
  },
  {
    name: 'Cancun',
    country: 'Mexico',
    countryCode: 'MX',
    description: 'A Caribbean paradise with stunning turquoise waters, ancient Mayan ruins, and vibrant nightlife.',
    travelTips: [
      'Book a day trip to Chichén Itzá early to beat crowds.',
      'Use the R1 bus for cheap travel along the hotel zone.',
      'Bring reef-safe sunscreen for the cenotes.',
      'Try authentic cochinita pibil tacos.',
    ],
    bestTimeToVisit: 'December–April for dry, sunny weather.',
    currency: 'Mexican Peso (MXN)',
    language: 'Spanish',
    timezone: 'EST (UTC-5)',
    topAttractions: ['Chichén Itzá', 'Cancun Underwater Museum', 'Playa Delfines', 'Isla Mujeres', 'Xcaret Park', 'Tulum Ruins'],
    travelCategories: ['beach', 'history', 'culture', 'food', 'nightlife'],
    estimatedBudget: { min: 700, max: 3000, currency: 'USD' },
    lat: 21.1619,
    lng: -86.8515,
    updatedAt: null as any,
  },

  // ── Oceania ────────────────────────────────────────────────────────────
  {
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    description: 'Australia\'s harbour city — iconic Opera House, stunning beaches, and a laid-back outdoor lifestyle.',
    travelTips: [
      'Take the Manly Ferry for breathtaking harbour views.',
      'Visit Bondi Beach early to secure a good spot.',
      'Book Opera House tickets for a performance, not just a tour.',
      'Explore the Rocks district for history and pubs.',
    ],
    bestTimeToVisit: 'October–April (warm months) for beach weather.',
    currency: 'Australian Dollar (AUD)',
    language: 'English',
    timezone: 'AEDT (UTC+11)',
    topAttractions: ['Sydney Opera House', 'Sydney Harbour Bridge', 'Bondi Beach', 'Taronga Zoo', 'The Rocks', 'Blue Mountains'],
    travelCategories: ['beach', 'nature', 'culture', 'food', 'outdoor'],
    estimatedBudget: { min: 1500, max: 5000, currency: 'AUD' },
    lat: -33.8688,
    lng: 151.2093,
    updatedAt: null as any,
  },
  {
    name: 'Maldives',
    country: 'Maldives',
    countryCode: 'MV',
    description: 'Paradise on Earth — crystal-clear turquoise waters, overwater bungalows, and incredible marine life.',
    travelTips: [
      'Book a resort with a house reef for the best snorkeling.',
      'Visit during the dry season for perfect weather.',
      'Pack reef-safe sunscreen to protect coral.',
      'Consider local island guesthouses for budget stays.',
    ],
    bestTimeToVisit: 'November–April (dry season) for perfect beach weather.',
    currency: 'Maldivian Rufiyaa (MVR)',
    language: 'Dhivehi',
    timezone: 'MVT (UTC+5)',
    topAttractions: ['Male Atoll', 'Biyadhoo Island', 'Manta Point', 'Dhigali Haa', 'Sunset Fishing', 'Biosphere Reserve'],
    travelCategories: ['beach', 'diving', 'romantic', 'luxury', 'nature'],
    estimatedBudget: { min: 2000, max: 10000, currency: 'USD' },
    lat: 3.2028,
    lng: 73.2207,
    updatedAt: null as any,
  },
];

/**
 * Run the seed script to populate Firestore with destination metadata.
 * Call this from your admin tooling or a one-off script.
 */
export async function runSeed(): Promise<void> {
  console.log('[SeedDestinations] Starting to seed destinations...');
  try {
    // Need to initialize Firebase first
    const { getFirebaseApp } = require('../firebase/firebaseApp');
    getFirebaseApp(); // force Firebase init
    await seedDestinations(SEED_DATA);
    console.log(`[SeedDestinations] Successfully seeded ${SEED_DATA.length} destinations.`);
  } catch (err) {
    console.error('[SeedDestinations] Error seeding:', err);
    throw err;
  }
}

// Allow direct execution: node -e "require('./src/scripts/seedDestinations').runSeed()"
// Or use ts-node with --compiler-options
if (require.main === module) {
  runSeed().catch(console.error);
}
