import { create } from 'zustand';
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
  updateDoc,
  where,
  type Unsubscribe,
} from 'firebase/firestore';

import { getFirebaseFirestore } from '@/src/firebase/firebaseApp';

export type Alert = {
  id: string;
  userId: string;
  tripId: string;
  category?: 'flight' | 'weather' | 'transport' | 'general' | 'check_in' | 'boarding' | 'gate' | 'baggage';
  severity: 'critical' | 'warning' | 'info' | 'low';
  title: string;
  message: string;
  /** Actionable next step generated by the monitoring engine */
  recommendation?: string;
  /** API source: openweather | aviationstack | system | ai */
  source?: 'openweather' | 'aviationstack' | 'system' | 'ai';
  active: boolean;
  read: boolean;
  createdAt?: any;
};

type AlertState = {
  alertsByTripId: Record<string, Alert[]>;
  userAlerts: Alert[];
  loading: boolean;
  error: string | null;

  startUserAlertsListener: (userId: string) => void;
  stopUserAlertsListener: () => void;

  startAlertsListener: (userId: string, tripId: string) => void;
  stopAlertsListener: (tripId: string) => void;

  markAllRead: (tripId: string) => Promise<void>;
};

const unsubByTrip: Record<string, Unsubscribe | undefined> = {};
let unsubUser: Unsubscribe | null = null;

function mapAlert(d: any): Alert {
  const data = d.data ? d.data() : d;
  const id   = d.id ?? data.id;
  const sevRaw = data.severity ?? 'info';
  const severity: Alert['severity'] =
    sevRaw === 'critical' || sevRaw === 'warning' || sevRaw === 'info' || sevRaw === 'low'
      ? sevRaw : 'info';
  return {
    id,
    userId:         data.userId         ?? '',
    tripId:         data.tripId         ?? '',
    category:       data.category       ?? 'general',
    severity,
    title:          data.title          ?? 'Alert',
    message:        data.message        ?? data.explanation ?? '',
    recommendation: typeof data.recommendation === 'string' ? data.recommendation : undefined,
    source:         data.source         ?? undefined,
    active:         Boolean(data.active ?? true),
    read:           Boolean(data.read   ?? false),
    createdAt:      data.createdAt,
  };
}

export const useAlertStore = create<AlertState>((set, get) => ({
  alertsByTripId: {},
  userAlerts: [],
  loading: false,
  error: null,

  /* =========================
     USER ALERTS
  ========================= */

  startUserAlertsListener: (userId) => {
    get().stopUserAlertsListener();
    set({ loading: true, error: null });

    const db = getFirebaseFirestore();
    const q = query(
      collection(db, 'alerts'),
      where('userId', '==', userId),
      orderBy('createdAt', 'desc')
    );

    unsubUser = onSnapshot(
      q,
      (snap) => {
        const alerts: Alert[] = snap.docs.map(mapAlert);
        set({ userAlerts: alerts, loading: false });
      },
      (err) => set({ loading: false, error: err?.message ?? 'Failed to load alerts' })
    );
  },

  stopUserAlertsListener: () => {
    if (unsubUser) { unsubUser(); unsubUser = null; }
    set({ userAlerts: [] });
  },

  /* =========================
     TRIP ALERTS
  ========================= */

  startAlertsListener: (userId, tripId) => {
    get().stopAlertsListener(tripId);
    set({ loading: true, error: null });

    const db = getFirebaseFirestore();
    const q = query(
      collection(db, 'alerts'),
      where('userId', '==', userId),
      where('tripId', '==', tripId),
      orderBy('createdAt', 'desc')
    );

    unsubByTrip[tripId] = onSnapshot(
      q,
      (snap) => {
        const alerts: Alert[] = snap.docs.map(mapAlert);
        set((state) => ({
          loading: false,
          alertsByTripId: { ...state.alertsByTripId, [tripId]: alerts },
        }));
      },
      (err) => set({ loading: false, error: err?.message ?? 'Failed to load alerts' })
    );
  },

  stopAlertsListener: (tripId) => {
    const unsub = unsubByTrip[tripId];
    if (unsub) { unsub(); delete unsubByTrip[tripId]; }
    set((state) => {
      const copy = { ...state.alertsByTripId };
      delete copy[tripId];
      return { alertsByTripId: copy };
    });
  },

  /* =========================
     MARK ALL READ
  ========================= */

  markAllRead: async (tripId) => {
    const db = getFirebaseFirestore();
    const alerts = get().alertsByTripId[tripId] ?? [];
    await Promise.all(
      alerts
        .filter((a) => !a.read)
        .map((a) => updateDoc(doc(db, 'alerts', a.id), { read: true }))
    );
  },
}));