// Auto-generated by downloadAirlines.cjs — do not edit manually
// Generated from OpenFlights Airlines dataset + curated overrides (2026-07-17T13:31:29.720Z)
// Contains 1169 active airlines

export type AirlineRecord = {
  i: string;   // iata
  c: string;   // icao
  n: string;   // name
  o: string;   // country
  s: string;   // callsign
  a: boolean;  // active
};

import airlinesData from '@/assets/airlines.json';

const data: AirlineRecord[] = airlinesData as AirlineRecord[];

export default data;
