// Auto-generated by downloadAirports.cjs — do not edit manually
// Generated from OurAirports dataset (2026-07-13T21:16:05.008Z)
// Contains 8803 airports with valid IATA codes

import type { AirportEntry } from '@/src/models/AirportEntry';
import airportsData from '@/assets/airports.json';

export type AirportRecord = {
  i: string;   // iata
  g: string;   // icao
  n: string;   // name
  m: string;   // municipality (city)
  c: string;   // countryCode
  l: [number, number]; // [lat, lng]
  t: string;   // type
};

const data: AirportRecord[] = airportsData as AirportRecord[];

export default data;
